### ISSUE TITLE
Not working with NextJs(SSR)

### ISSUE THREAD

**Issue by ZKMN** [michelonsouza/encrypt-storage#236]
**Describe the bug**
ReferenceError: self is not defined

**To Reproduce**
Install this package in project with next js

**Additional context**
I guess this is due to the special behavior of the localStorage in the nextJs. I mean document or window should be defined for work with localStorage.

**Comment by michelonsouza** [comment]
I don't work with Next, at least not yet, and I'm not sure how it works with the browser's window object. If you have a solution I would be very happy to accept your PR. Otherwise let me know here so I can try to better understand the use of window in Next.

**Comment by michelonsouza** [comment]
I sent a new release. You can test to see if it doesn't cause errors, please. Thanks.

**Comment by ZKMN** [comment]
Hit, thx. But still self is not defined.

**Comment by michelonsouza** [comment]
Thanks for finding a solution. I will remember whenever I have a new issue.
