### ISSUE TITLE
[question] BADENGINE

### ISSUE THREAD

**Issue by aspann** [michelonsouza/encrypt-storage#429]
Hi,
sorry for not using the pre-defined issue template, as this is hopefully neither a bug nor an enhancement.. But I'm kinda lost and maybe someone can bring light into the dark.. 

Since I updated my project to the latest version of encrypt-storage I got this strange warning:
```bash
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'encrypt-storage@2.4.5',
npm WARN EBADENGINE   required: { npm: 'You must run yarn in this project', yarn: '1.22.x' },
npm WARN EBADENGINE   current: { node: 'v18.7.0', npm: '8.17.0' }
npm WARN EBADENGINE }
```

Can someone explain me what exacly this means. (yeah using yarn - haha, but with 3.7.x it worked flawlessly using npm)
Or in other words, is this critical or ignorable?

Many thanks in advance.

**Comment by michelonsouza** [comment]
Hello @aspann,
I fixed the minimal version of yarn.
Can you download the latest version and compare to see if the problem persists?

Thank you very much.

**Comment by michelonsouza** [comment]
I apologize for the delay.
But it's been a while since I asked if everything is OK and got no response.

I will close the issue and it can be reopened at any time.

Thank you very much.

**Comment by avenmore** [comment]
I've also been seeing this recently (can't remember when it started). Just saw it again now when updating to 2.10.2, so came here to see if it is known. I use npm, not yarn.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'encrypt-storage@2.10.2',
npm WARN EBADENGINE   required: { npm: 'You must run yarn in this project', yarn: '^1.22.x' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.18.0' }
```

**Comment by michelonsouza** [comment]
I'll test again on linux to make sure I got it right.

Sorry about that, I'll reopen the issue.

Thanks.

**Comment by michelonsouza** [comment]
Hi @avenmore, I think I solved the problem.
Can you update to the latest version, please and test to see if warn persists?

Thank you very much.

**Comment by avenmore** [comment]
Hi @michelonsouza
Confirmed that the messages no longer appear when updating to 2.12.2.
Thanks very much for attending to this :)

**Comment by michelonsouza** [comment]
Thanks to you @avenmore for making the library better.

Any problem can open a new issue.

Thank you again.
