### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by skp92** [michelonsouza/encrypt-storage#505]
**Describe the bug**
After installing this package and running the app I am getting this error.

![image](https://user-images.githubusercontent.com/29480323/192769790-b50da972-5967-4bbe-adb1-ac16f4bebe18.png)

Can somebody check?

Node version - 14.19.1

**Comment by michelonsouza** [comment]
Hello @skp92, how are you?
I will analyze this, can you tell me if you are using it with CRA, Vite, NextJS or pure webpack?

Thank you very much.

**Comment by michelonsouza** [comment]
Meanwhile, I made a change in version 2.12.9, could you please update and check if the error still persists?
Thank you very much.

**Comment by skp92** [comment]
> Hello @skp92, how are you? I will analyze this, can you tell me if you are using it with CRA, Vite, NextJS, Angular or pure webpack?
> 
> Thank you very much.

Hi @michelonsouza , thank you for checking this. I am using with React app, after update issue got fixed. We are good to close this issue.
