### ISSUE TITLE
decryptValue get method return null for plain data

### ISSUE THREAD

**Issue by skp92** [michelonsouza/encrypt-storage#547]
**Describe the bug**
When trying to read encrypted data from LS and using decryptValue, getting result as null.

**Expected behavior**
The data which was encrypted and stored back in LS should be retrieved back by using decrypt method

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser - Application
 - Version 16.04

**Additional context**
While using decryptString, it says it is deprecated by decryptValue

**Comment by skp92** [comment]
@michelonsouza , hope you are doing well. Can you please check this? Any plain data(boolean false, empty string, empty object) which are encrypted and while trying to decrypt and store back to LS, getItem is returning undefined for such data, decryptValue is returning null. Is this is a limitation for this library?

**Comment by michelonsouza** [comment]
Hello @skp92, the case is that encryptValue and decryptValue just encrypt and decrypt data. They are not used in conjunction with local storage. Only standalone to use as outside the context of Storage. For items in a Storage use the previously defined encryptStorage instance.

I don't know if I answered your question correctly.
