### ISSUE TITLE
Invalid left-hand side in assignment (Angular)

### ISSUE THREAD

**Issue by kisimediaDE** [michelonsouza/encrypt-storage#583]
Hey, I'm using your plugin in an angular application. 
Since some weeks I have the problem, that when I try to deploy the application to the server I get the message "Invalid left-hand side in assignment"
No I was able to figure out the issue. 

It's caused by two lines of your code: 
```
window && window?.globalThis && (window?.globalThis.AsyncEncryptStorage = A)
window && window?.globalThis && (window?.globalThis.EncryptStorage = b)
```

And appears since this commit: 296629d8444f57d1b180fc43d1062b4e026439be and/or 85d2e7dbdcbd54535c71199c32742158aee07c98

I can run the app again if I remove the `?` behind `window`. 
I'm not sure why you using this when you checking before if window is defined?

I hope you know what I mean and you can help me with this issue. 
Thank you so much already! :-)

(If you need more information, please ask!)

**Comment by kisimediaDE** [comment]
The latest version that is working is 2.12.8
After this it breaks with the "Invalid left-hand side in assignment" error message

**Comment by michelonsouza** [comment]
Hello @kisimediaDE, hope you are doing well.
I'm going to adjust this, I put this code to always have a representation in the window interface. Looks like that ended up backfiring.

But I find it strange, because I'm doing validations, like the ones below:

```typescript
/* istanbul ignore next */
if (window) {
  /* istanbul ignore next */
  (window as any).EncryptStorage = EncryptStorage;
}

/* istanbul ignore next */
if (window && window?.globalThis) {
  /* istanbul ignore next */
  (window?.globalThis as any).EncryptStorage = EncryptStorage;
}
```
The compiled code that must be causing this mess.

I promise to fix it in the next implementations.

Thank you very much.

**Comment by Sireini** [comment]
@michelonsouza I am facing the same issue, this will not be fixed?

**Comment by kisimediaDE** [comment]
I agree still the same issue with the latest version @michelonsouza

**Comment by aspann** [comment]
I'm a bit confused. You say that you promise to fix it, but the issue is closed with the label "wontfix".

So what is the state here? (we also facing this issue in several projects)
