### ISSUE TITLE
Can't getItem

### ISSUE THREAD

**Issue by fernandofas** [michelonsouza/encrypt-storage#589]
**Describe the bug**

Got to create a new instance in one component:
`new EncryptStorage('cid', { prefix: '@instance1', });`

And tried to get the value in another component:
`const token = encryptStorage.getItem<T = any>('cid');`

Console message:
`'encryptStorage' is not defined  no-undef`

Using Windows 10,
VSCode,
React

Any idea?

**Comment by michelonsouza** [comment]
Hello @fernandofas , I hope you are well.
Unless you assign the `encrypt-storage` instance to the window it will never exist in the global context, and I don't advise doing that in production.

in any `<filename>.d.ts` file declare this module:
```typescript
import { EncryptStorage } from 'encrypt-storage';

declare global {
  export interface Window {
    encryptStorage?: EncryptStorage;
  }
}
```
After that, where to declare your `encrypt-storage` instance use this code:
```typescript
const encryptStorage = new EncryptStorage('@secretkey', { prefix: '@instance1' });

window.encryptStorage = encryptStorage;
```

Hope this helps.

Thanks.

**Comment by fernandofas** [comment]
Hi there,

I'm not using ts files and where do I suppose to place this:

declare global {
  export interface Window {
    encryptStorage?: EncryptStorage;
  }
}

Kind regards,

Fernando Fas

**Comment by fernandofas** [comment]
If you can send an example that would be clear and would help many other
users avoiding sending issues statements on github.

Kind regards,

Fernando Fas
