### ISSUE TITLE
Mocking localStorage when Unit Testing Modules using Pinia/Encrypt-Storage

### ISSUE THREAD

**Issue by jhuerta** [michelonsouza/encrypt-storage#590]
Hi,

We are using Vue 3 and Pinia with Encrypt-Storage.

We are implementing some unit tests in Vue and we need to mock the localStorage behind Encrypt-Storage/Pinia.

As we are using Vitest, it seems the way to is using the following package vitest-localstorage-mock.

My questions are: Do you suggest any other way to implement the unit tests of the modules using Pinia/Encrypt-Storage ? Any code example?

Thanks,

Juan

**Comment by michelonsouza** [comment]
Hi @jhuerta, hope you are doing well.
To be honest, I haven't used `encrypt-storage` with `vitest` yet.
I believe that you are performing tests of the encryption itself. Third-party package testing, just in case.
I would mock `encrypt-storage` and use a bypass. Mocking the value itself, or just encrypting with `EncryptStorage.encryptValue` and comparing the values.

I'm sorry for not answering earlier and if I didn't answer your question properly.
I'm pretty busy at work.

But I'm here and available.

Thanks.
